---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
    - '**.js'
    - '**.jsx'
exclude_paths:
  - dist/
  - lib/
  - docs/
  - assets/
