env:
  browser: true
  es6: true
extends:
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins: []
# Be sure rules do not conflict with prettier
rules: {}
overrides:
  - files: ['./demos*.js']
    excludedFiles: './demos/*.js'
